name: Cléverton Heming
description: >
  ......
about: >
  .....

master_repo: false
url: "https://cleverton.com.br"
markdown: kramdown
highlighter: rouge

plugins: ["jekyll-paginate", "jekyll-gist", "jekyll-feed"]

paginate: 4

logo: logo.png
disqus_shortname:

rtl: false
owner:
  name: whitepaper
  avatar: "https://www.gravatar.com/avatar/9c92614837bcd20eefd73ec1134600b6?s=328&d=identicon&r=PG&f=1"
  email: "oi@cleverton.com.br"
  # Social networking links used in footer. Update and remove as you like.
  twitter: clevertonh
  github: https://github.com/clevertonh
  stackexchange: https://stackoverflow.com/users/6440384/cl%c3%a9verton-heming?tab=profile
  linkedin:
  # For Google Authorship https://plus.google.com/authorship
  google_plus:

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:
